trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)'
  projectFolder: 'HelloAzureWebApp'

stages:

- stage: Build
  displayName: 'Build and Test'
  jobs:
    - job: Build
      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '8.0.x'

        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'Build project'
          workingDirectory: '$(projectFolder)'

        - script: dotnet test --no-restore --verbosity normal
          displayName: 'Run unit tests'
          workingDirectory: '$(projectFolder)'

        - script: dotnet publish --configuration $(buildConfiguration) --output $(outputDir)
          displayName: 'Publish app'
          workingDirectory: '$(projectFolder)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(outputDir)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: DeployWeb
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  artifactName: 'drop'

              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'azureconnect'
                  appType: 'webApp'
                  appName: 'helloazurewebapp-dev'
                  package: '$(Pipeline.Workspace)/drop'
