trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)'
  projectFolder: 'HelloAzureWebApp'
  webAppName: 'helloazurewebapp-dev'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
    - job: Build
      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '8.0.x'

        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'Build project'
          workingDirectory: '$(projectFolder)'

        - script: dotnet test --no-restore --verbosity normal
          displayName: 'Run unit tests'
          workingDirectory: '$(projectFolder)'

        - script: dotnet publish --configuration $(buildConfiguration) --output $(outputDir)
          displayName: 'Publish app'
          workingDirectory: '$(projectFolder)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(outputDir)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: DeployWeb
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureKeyVault@2
                inputs:
                  azureSubscription: 'azureconnect'
                  KeyVaultName: 'my-kevault-devops'
                  SecretsFilter: 'MyAppPassword'
                  RunAsPreJob: true

              - task: DownloadBuildArtifacts@0
                inputs:
                  artifactName: 'drop'

              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'azureconnect'
                  appType: 'webApp'
                  appName: '$(webAppName)'
                  package: '$(Pipeline.Workspace)/drop'

              - script: |
                  echo "Verifying deployment at: https://$(webAppName).azurewebsites.net"
                  for i in {1..5}
                  do
                    echo "Attempt $i..."
                    curl -I https://$(webAppName).azurewebsites.net && break
                    echo "Retrying in 10 seconds..."
                    sleep 10
                  done
                displayName: 'Verify deployment with retries'
